server:
  port: 8082
  contextPath: /products

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: password
    driver-class: com.mysql.jdbc.Driver

  jpa:
   hibernate:
      ddl-auto: create
   dialect: default

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8081/auth/oauth/token

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5